version: 2.1
orbs:
    node: cimg/node:lts
executors:
    default:
        docker:
            - image: cimg/base:stable
        working_directory: ~/repo
jobs:
    test:
        executor: default
        steps:
            - checkout
            - node/install:
                node-version: '22'
            - restore_cache:
                key: node_modules-2-{{ checksum "package.json" }}-{{ checksum "package-lock.json"}}
            - run: npm ci
            - save_cache:
                paths:
                    - $HOME/.npm
                key: node_modules-2-{{ checksum "package.json" }}-{{ checksum "package-lock.json"}}
            # ログディレクトリの作成
            - run:
                command: |
                    mkdir -p results
                    mkdir -p results/eslint
            - run:
                name: eslint
                command: npm run lint -- --format=html -o ./results/eslint/eslint.html
            - run:
                name: Run tests
                command: npm test -- --ci --runInBand
            - store_test_results:
                path: results
            - store_artifacts:
                path: results
            - run: npm run build
            - persist_to_workspace:
                root: ~/repo
                paths:
                    - dist
workflows:
    version: 2
    workflow:
        jobs:
            - test
